### ISSUE TITLE
v0.4.3 does not specify peer-dependencies

### ISSUE THREAD

**Issue by LevelbossMike** [mjanjic01/ember-konva#4]
Thanks for this addon 👏 

The current release (0.4.3) of this addon published to npm does not specify konva as a peer-dependency which will break all applications that use this addon - I tried with a brand new app created via ember-cli 4.1.0.

[The fix](https://github.com/mjanjic01/ember-konva/commit/7b5ff6c4d7acf112afa77b7fdbc556219d7f8b72#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R61) is already included on the master branch on github. Would be great if this version could be published as 0.4.4.

Thanks again for the work on this addon, very cool project 🍻

**Comment by mjanjic01** [comment]
Hi there @LevelbossMike,
version 0.4.4 with the peer-dependency fix has been published to npm.
Have fun 😄

**Comment by LevelbossMike** [comment]
@mjanjic01 Thanks so much!
